name: Build and Release

on:
  release:
    types: [published]
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build Binary
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        mkdir -p dist
        if [ "$GOOS" = "windows" ]; then
          BIN_NAME="dd.exe"
        else
          BIN_NAME="dd"
        fi
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o "dist/${BIN_NAME}" ./cmd/main.go

    - name: Archive the binary
      if: github.event_name == 'release'
      run: |
        VERSION=${{ github.event.release.tag_name }}
        ZIP_NAME="dd-${VERSION}-${{ matrix.os }}-${{ matrix.arch }}.zip"
        cd dist
        zip "$ZIP_NAME" dd* 
        cd ..

    - name: Upload Binaries to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

